/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.cifrassignificativas;

import controladores.OyenteBotonesCS;
import javax.swing.JTextArea;
import modelos.CifrasSignificativas;

/**
 *
 * @author jarv
 */
public class PanelOperacionesCS extends javax.swing.JPanel {

    /**
     * Creates new form PanelCifrasSignificativas
     */
    public PanelOperacionesCS(CifrasSignificativas cifrasSignificativas) {
        initComponents();
        cifrasSignificativas.setCampoNumerosOperaciones(campoNumeros);
        cifrasSignificativas.setCampoResultadosOperaciones(campoResultados);
        addEventos(new OyenteBotonesCS(cifrasSignificativas, this));
    }
    
    public final void addEventos(OyenteBotonesCS oyente) {
        botonSumar.addActionListener(oyente);
        botonRestar.addActionListener(oyente);
        botonMultiplicar.addActionListener(oyente);
        botonDividir.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        labelOperacionesCS = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();
        panelNumeros = new javax.swing.JScrollPane();
        campoNumeros = new javax.swing.JTextArea();
        panelCampoResultados = new javax.swing.JPanel();
        panelTextAreaCampoResultados = new javax.swing.JScrollPane();
        campoResultados = new javax.swing.JTextArea();
        panelSur = new javax.swing.JPanel();
        botonSumar = new javax.swing.JButton();
        botonRestar = new javax.swing.JButton();
        botonMultiplicar = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        setLayout(new java.awt.BorderLayout());

        labelOperacionesCS.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelOperacionesCS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOperacionesCS.setText("Operaciones de Cifras Significativas");
        labelOperacionesCS.setToolTipText("");
        panelNorte.add(labelOperacionesCS);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setLayout(new java.awt.BorderLayout());

        panelNumeros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Introduce Valores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        campoNumeros.setColumns(20);
        campoNumeros.setRows(5);
        panelNumeros.setViewportView(campoNumeros);

        panelCentro.add(panelNumeros, java.awt.BorderLayout.CENTER);

        panelCampoResultados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelCampoResultados.setLayout(new java.awt.BorderLayout());

        campoResultados.setEditable(false);
        campoResultados.setColumns(20);
        campoResultados.setRows(5);
        panelTextAreaCampoResultados.setViewportView(campoResultados);

        panelCampoResultados.add(panelTextAreaCampoResultados, java.awt.BorderLayout.SOUTH);

        panelCentro.add(panelCampoResultados, java.awt.BorderLayout.SOUTH);

        add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setLayout(new java.awt.GridLayout(1, 4, 10, 10));

        botonSumar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        botonSumar.setText("Sumar");
        botonSumar.setName("sumar"); // NOI18N
        botonSumar.setPreferredSize(new java.awt.Dimension(100, 40));
        panelSur.add(botonSumar);

        botonRestar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        botonRestar.setText("Restar");
        botonRestar.setName("restar"); // NOI18N
        botonRestar.setPreferredSize(new java.awt.Dimension(100, 40));
        panelSur.add(botonRestar);

        botonMultiplicar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        botonMultiplicar.setText("Multiplicar");
        botonMultiplicar.setName("multiplicar"); // NOI18N
        botonMultiplicar.setPreferredSize(new java.awt.Dimension(100, 40));
        panelSur.add(botonMultiplicar);

        botonDividir.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        botonDividir.setText("Dividir");
        botonDividir.setName("dividir"); // NOI18N
        botonDividir.setPreferredSize(new java.awt.Dimension(100, 40));
        panelSur.add(botonDividir);

        add(panelSur, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonMultiplicar;
    private javax.swing.JButton botonRestar;
    private javax.swing.JButton botonSumar;
    private javax.swing.JTextArea campoNumeros;
    private javax.swing.JTextArea campoResultados;
    private javax.swing.JLabel labelOperacionesCS;
    private javax.swing.JPanel panelCampoResultados;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JScrollPane panelNumeros;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane panelTextAreaCampoResultados;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLabelCS() {
        return labelOperacionesCS;
    }
    
    public JTextArea getCampoNumeros() {
        return campoNumeros;
    }

}
