/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.cifrassignificativas;

import javax.swing.JTabbedPane;
import modelos.CifrasSignificativas;

/**
 *
 * @author jarv
 */
public class PanelesCS extends javax.swing.JPanel {

    /**
     * Creates new form PanelesCS
     */
    public PanelesCS(CifrasSignificativas cifrasSignificativas) {
        initComponents();
        pestanasPaneles.addTab("Contador", new PanelContadorCS(cifrasSignificativas));
        pestanasPaneles.addTab("Operaciones", new PanelOperacionesCS(cifrasSignificativas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestanasPaneles = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(pestanasPaneles, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JTabbedPane getPestanasPaneles() {
        return pestanasPaneles;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane pestanasPaneles;
    // End of variables declaration//GEN-END:variables
}
