/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.tiposerrores;

import controladores.OyenteBotonesTiposDeErrores;
import modelos.TiposDeErrores;

/**
 *
 * @author jarv
 */
public class PanelTiposDeErrores extends javax.swing.JPanel {

    /**
     * Creates new form PanelTiposDeErrores
     */
    public PanelTiposDeErrores(TiposDeErrores tiposDeErrores) {
        initComponents();
        tiposDeErrores.setCampoResultados(campoResultados);
        tiposDeErrores.setComboValores(comboValores);
        tiposDeErrores.setComboValores1(comboValores1);
        tiposDeErrores.setCampoValor(campoValor);
        tiposDeErrores.setCampoValor1(campoValor1);
        addEventos(new OyenteBotonesTiposDeErrores(tiposDeErrores, this));
    }
    
    public final void addEventos(OyenteBotonesTiposDeErrores oyente) {
        botonCalcular.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTiposDeErrores = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        comboValores = new javax.swing.JComboBox();
        campoValor = new javax.swing.JTextField();
        comboValores1 = new javax.swing.JComboBox();
        campoValor1 = new javax.swing.JTextField();
        panelCentro = new javax.swing.JPanel();
        panelTexArea = new javax.swing.JScrollPane();
        campoResultados = new javax.swing.JTextArea();
        panelSur = new javax.swing.JPanel();
        botonCalcular = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        setLayout(new java.awt.BorderLayout());

        panelNorte.setLayout(new java.awt.BorderLayout());

        labelTiposDeErrores.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelTiposDeErrores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTiposDeErrores.setText("Calculo de Tipos de Errores");
        labelTiposDeErrores.setToolTipText("");
        panelTitulo.add(labelTiposDeErrores);

        panelNorte.add(panelTitulo, java.awt.BorderLayout.NORTH);

        panelCampos.setLayout(new java.awt.GridLayout(3, 2));

        comboValores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Valor Verdadero", "Valor Aproximado", "Error Verdadero" }));
        panelCampos.add(comboValores);
        panelCampos.add(campoValor);

        comboValores1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Valor Verdadero", "Valor Aproximado", "Error Verdadero" }));
        comboValores1.setSelectedIndex(1);
        panelCampos.add(comboValores1);
        panelCampos.add(campoValor1);

        panelNorte.add(panelCampos, java.awt.BorderLayout.CENTER);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        panelCentro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Resultados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        panelCentro.setLayout(new java.awt.BorderLayout());

        campoResultados.setEditable(false);
        campoResultados.setColumns(20);
        campoResultados.setRows(5);
        panelTexArea.setViewportView(campoResultados);

        panelCentro.add(panelTexArea, java.awt.BorderLayout.CENTER);

        add(panelCentro, java.awt.BorderLayout.CENTER);

        panelSur.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        panelSur.setLayout(new java.awt.BorderLayout());

        botonCalcular.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        botonCalcular.setText("Calcular");
        botonCalcular.setPreferredSize(new java.awt.Dimension(100, 40));
        panelSur.add(botonCalcular, java.awt.BorderLayout.SOUTH);

        add(panelSur, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JTextArea campoResultados;
    private javax.swing.JTextField campoValor;
    private javax.swing.JTextField campoValor1;
    private javax.swing.JComboBox comboValores;
    private javax.swing.JComboBox comboValores1;
    private javax.swing.JLabel labelTiposDeErrores;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane panelTexArea;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getCampoValor() {
        return campoValor;
    }

    public javax.swing.JTextField getCampoValor1() {
        return campoValor1;
    }
    
}
