/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import javax.swing.border.TitledBorder;
import modelos.ConceptosRandomInicio;

/**
 *
 * @author jarv
 */
public class PanelInicio extends javax.swing.JPanel {

    private ConceptosRandomInicio conceptosRandomInicio;
    private ImageIcon imagenIcon;

    /**
     * Creates new form PanelBienvenida
     */
    public PanelInicio(ConceptosRandomInicio conceptosRandomInicio) {
        initComponents();
        this.conceptosRandomInicio = conceptosRandomInicio;
        imagenIcon = conceptosRandomInicio.getImagenRandom();
        add(new PanelCentro(), BorderLayout.CENTER);
        etiquetaTitulo.setText(imagenIcon.getDescription());
        campoDefinicion.setText(conceptosRandomInicio.getDefinicion(imagenIcon.getDescription()));
    }

    private class PanelCentro extends JPanel {
        
        public PanelCentro() {
            this.setBorder(BorderFactory.createTitledBorder(null, "Ejemplo", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));
        }

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            Image imagen = imagenIcon.getImage();
            int ancho = (this.getWidth() / 2) - ((imagen.getWidth(null)) / 2);
            int alto = (this.getHeight() / 2) - ((imagen.getHeight(null)) / 2);
            g.drawImage(imagen, ancho, alto, null);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        panelSur = new javax.swing.JPanel();
        panelTextArea = new javax.swing.JScrollPane();
        campoDefinicion = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
        setLayout(new java.awt.BorderLayout());

        panelNorte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Concepto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        etiquetaTitulo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        panelNorte.add(etiquetaTitulo);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        panelSur.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Definicion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelSur.setLayout(new java.awt.BorderLayout());

        panelTextArea.setPreferredSize(new java.awt.Dimension(244, 50));

        campoDefinicion.setEditable(false);
        campoDefinicion.setColumns(20);
        campoDefinicion.setRows(5);
        panelTextArea.setViewportView(campoDefinicion);

        panelSur.add(panelTextArea, java.awt.BorderLayout.SOUTH);

        add(panelSur, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campoDefinicion;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane panelTextArea;
    // End of variables declaration//GEN-END:variables
}
