/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.OyenteMenus;
import controladores.OyenteVentana;
import java.awt.event.InputEvent;
import javax.swing.JMenuItem;
import javax.swing.KeyStroke;
import modelos.ConceptosRandomInicio;

/**
 *
 * @author jarv
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrameCifrasSignificativas
     */
    public VentanaPrincipal() {
        initComponents();
        this.setFocusable(true);
        add(new PanelInicio(new ConceptosRandomInicio()));
        this.addWindowListener(new OyenteVentana(this));
        opcionAbrir.setEnabled(false);
        addEventos(new OyenteMenus(this));
    }
    
    public void addEventos(OyenteMenus oyente) {
        opcionSalir.addActionListener(oyente);
        opcionAbrir.addActionListener(oyente);
        this.addKeyListener(oyente);
        opcionCifrasSignificativas.addActionListener(oyente);
        opcionTiposErrores.addActionListener(oyente);
        ayudaCifrasSignificativas.addActionListener(oyente);
        ayudaTiposDeErrores.addActionListener(oyente);
        opcionAcercaDe.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desconocido = new javax.swing.JMenuItem();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        opcionAbrir = new javax.swing.JMenuItem();
        separadorArchivo = new javax.swing.JPopupMenu.Separator();
        opcionSalir = new javax.swing.JMenuItem();
        menuHerramientas = new javax.swing.JMenu();
        opcionCifrasSignificativas = new javax.swing.JMenuItem();
        separadorHerramientas = new javax.swing.JPopupMenu.Separator();
        opcionTiposErrores = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        ayudaCifrasSignificativas = new javax.swing.JMenuItem();
        ayudaTiposDeErrores = new javax.swing.JMenuItem();
        separadorAyuda = new javax.swing.JPopupMenu.Separator();
        opcionAcercaDe = new javax.swing.JMenuItem();

        desconocido.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CSYTE");

        menuArchivo.setText("Archivo");

        opcionAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        opcionAbrir.setMnemonic('A');
        opcionAbrir.setText("Abrir");
        opcionAbrir.setName("abrir"); // NOI18N
        menuArchivo.add(opcionAbrir);
        menuArchivo.add(separadorArchivo);

        opcionSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        opcionSalir.setMnemonic('S');
        opcionSalir.setText("Salir");
        opcionSalir.setName("salir"); // NOI18N
        menuArchivo.add(opcionSalir);

        barraMenu.add(menuArchivo);

        menuHerramientas.setText("Herramientas");

        opcionCifrasSignificativas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        opcionCifrasSignificativas.setMnemonic('C');
        opcionCifrasSignificativas.setText("Cifras Significativas");
        opcionCifrasSignificativas.setName("cifrasSignificativas"); // NOI18N
        menuHerramientas.add(opcionCifrasSignificativas);
        menuHerramientas.add(separadorHerramientas);

        opcionTiposErrores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        opcionTiposErrores.setMnemonic('T');
        opcionTiposErrores.setText("Tipos de Errores");
        opcionTiposErrores.setName("tiposDeErrores"); // NOI18N
        menuHerramientas.add(opcionTiposErrores);

        barraMenu.add(menuHerramientas);

        menuAyuda.setText("Ayuda");
        menuAyuda.setName("ayuda"); // NOI18N

        ayudaCifrasSignificativas.setText("Cifras Significativas");
        ayudaCifrasSignificativas.setName("ayudaCifrasSignificativas"); // NOI18N
        menuAyuda.add(ayudaCifrasSignificativas);

        ayudaTiposDeErrores.setText("Tipos de Errores");
        ayudaTiposDeErrores.setName("ayudaTiposDeErrores"); // NOI18N
        menuAyuda.add(ayudaTiposDeErrores);
        menuAyuda.add(separadorAyuda);

        opcionAcercaDe.setText("Acerca De");
        opcionAcercaDe.setName("acercaDe"); // NOI18N
        menuAyuda.add(opcionAcercaDe);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getOpcionAbrir() {
        return opcionAbrir;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ayudaCifrasSignificativas;
    private javax.swing.JMenuItem ayudaTiposDeErrores;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem desconocido;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuHerramientas;
    private javax.swing.JMenuItem opcionAbrir;
    private javax.swing.JMenuItem opcionAcercaDe;
    private javax.swing.JMenuItem opcionCifrasSignificativas;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JMenuItem opcionTiposErrores;
    private javax.swing.JPopupMenu.Separator separadorArchivo;
    private javax.swing.JPopupMenu.Separator separadorAyuda;
    private javax.swing.JPopupMenu.Separator separadorHerramientas;
    // End of variables declaration//GEN-END:variables
}
